// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserRole2 = "user_roles2"

// UserRole mapped from table <user_roles>
type UserRole2 struct {
	UserID int64  `gorm:"column:user_id;primaryKey" json:"user_id"`
	RoleID string `gorm:"column:role_id;primaryKey;comment:'primary Key is ID'" json:"role_id"` // 'primary Key is ID'
}

// TableName UserRole's table name
func (*UserRole) TableName2() string {
	return TableNameUserRole
}
