// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserRole = "user_roles"

// UserRole mapped from table <user_roles>
type UserRole struct {
	UserID int64  `gorm:"column:user_id;primaryKey" json:"user_id"`
	RoleID string `gorm:"column:role_id;primaryKey;comment:'primary Key is ID'" json:"role_id"` // 'primary Key is ID'
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
