server:
  port: 8080
  mode: "dev"

mysql:
  host: mysql_container  # 127.0.0.1
  port: 3306
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600   # 1 minute

logger:
  log_level: debug
  file_log_name: ./storages/logs/dev.001.log
  MaxSize:    500     # megabytes
  MaxBackups: 3
  MaxAge:     28      # days
  Compress:   true    # disabled by default

redis:
  host: redis_container  # 127.0.0.1
  port: 6379
  password:
  db: 0
  pool_size: 100