server:
  port: 8080
  mode: dev

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10  # so luong ket noi toi da trong pool connection
  maxOpenConns: 10 # so luong ket noi mo toi da trong pool connection, nen kiem soat cai nay, khong de mac dinh
  connMaxLifeTime: 3600 # vong doi toi da cua 1 connection

logger:
  logLevel: debug
  fileLogName: "./storages/logs/dev.001.txt"
  maxSize: 500
  maxBackups: 3
  maxAge: 28
  compress: true

redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 0